GET http://localhost:3200/

###

GET https://lowback-wjumd.ondigitalocean.app/db/
Authorization: jwt tokenMaster

###

GET http://localhost:3000/db/query/test2
Authorization: jwt token222222222222

###

GET http://localhost:3000/db/reload

###

POST http://localhost:3000/db/set/test3/eee/e2/2
content-type: application/json
Authorization: jwt tokenMaster

{
    "22": "422244",
    "eee": 44
}

###

POST http://localhost:3000/db/merge/test3/eee
content-type: application/json

{
    "ddd": "tessss",
    "ggg": 454
}

###

GET http://localhost:3000/db/delete/test3/eee/ddd
content-type: application/json

###   Auth

GET http://localhost:3000/auth/site2/1234567890
content-type: application/json

###

GET http://localhost:3000/admin
Authorization: jwt tokenMaster
